services:
  nginx-web-server:
    image: nginx:alpine
    container_name: nginx-web-server

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.crt:/etc/ssl/nginx.crt:ro
      - ./nginx.private.key:/etc/ssl/nginx.private.key:ro

    restart: unless-stopped